import { createUseStyles } from "react-jss";
export const useStyles = createUseStyles(theme => ({
  "@global": {
    "*": {
      margin: 0,
      padding: 0,
      boxSizing: "border-box",
    },
    body: { backgroundColor: theme.primary, transition: "all 0.5s linear" },
  },
  navbar: {
    backgroundColor: theme.secondary,
    color: theme.primary,
    position: "relative",
    display: "-webkit-box",
    display: "-ms-flexbox",
    display: "flex",
    msFlexWrap: "wrap",
    flexWrap: "wrap",
    webkitBoxAlign: "center",
    msGlexAlign: "center",
    alignItems: "center",
    webkitGoxPack: "justify",
    msFlexPack: "justify",
    justifyContent: "space-between",
    padding: "0.5rem 1rem",
    flexBasis: "auto",
    webkitBoxFlex: 1,
    msFlexPositive: 1,
    flexGrow: 1,
    webkitBoxAlign: "center",
    msFlexAlign: "center",
    transition: "all 0.5s linear",
  },

  nav: {
    display: "-webkit-box",
    display: " -ms-flexbox",
    display: "flex",
    paddingLeft: 0,
    marginBottom: 0,
    listStyle: "none",
    webkitBoxOrient: "horizontal",
    webkitBoxDirection: "normal",
    msFlexDirection: "row",
    flexDirection: "row",
    marginBlockStart: "1em",
    marginBlockEnd: "1em",
    marginInlineStart: "0px",
    marginInlineEnd: "0px",
    paddingInlineStart: "40px",
    "& li": {
      "& a": {
        padding: "2rem",
      },
    },
  },

  container: {
    width: "100%",
    height: "500px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  themeButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.primary,
    width: "300px",
    height: "400px",
    transition: "all 0.5s linear",
    color: theme.primary,
    borderRight: `2px solid ${theme.primary}`,
    backgroundColor: theme.secondary,
  },
  themeButton1: {
    color: theme.primary,
    borderRight: theme.primary,
    backgroundColor: theme.secondary,
  },
  themeButton2: {
    color: theme.secondary,
    borderRight: theme.secondary,
    backgroundColor: theme.primary,
  },
}));
